version: "3"

services:
  redis-shortener:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - webnet
    command: ["redis-server", "--save", "60", "1"]

  shortener:
    build: .
    environment:
      REDIS_URL: "redis://redis-shortener:6379/0"
    ports:
      - "8080:8080"
    depends_on:
      - redis-shortener
    networks:
      - webnet

volumes:
  logs:
  conf:

networks:
  webnet:

